id = "mote"
name = "Mote"
version = "0.1.0"
schema_version = 1
authors = ["Warith Ogunwoolu"]
description = "Mote language support: syntax highlighting, outline, brackets and indents."
repository = "https://github.com/Bluewraith04/mote"

[grammars.mote]
repository = "https://github.com/Bluewraith04/mote"
rev = "8acb851d6d1d7d750ef5ebef77968e568cb43e81"
path = "editors/tree-sitter-mote"
