[package]
name = "modules"
version = "0.1.2"
edition = "2021"
license = "MIT"

[dependencies]
compiler = { path = "../compiler" }
contracts = { path = "../contracts" }
bincode = "1.3"
sha2 = "0.10"

[build-dependencies]
sha2 = "0.10"

[dev-dependencies]
runtime = { path = "../runtime" }
isa = { path = "../isa" }
ffi = { path = "../ffi" }
gc = { path = "../gc" }
