use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;
use crate::resolver::ResolvedPackage;
use crate::semver::Version;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
/// One pinned package in `mote.lock`.
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    pub source: String,
    #[serde(default)]
    pub checksum: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
/// The contents of `mote.lock`.
pub struct Lockfile {
    pub version: u32,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    pub fn new(packages: Vec<LockedPackage>) -> Self {
        let mut pkgs = packages;
        pkgs.sort_by(|a, b| a.name.cmp(&b.name));
        Self {
            version: 1,
            packages: pkgs,
        }
    }

    pub fn from_resolved(resolved: &[ResolvedPackage]) -> Self {
        let pkgs = resolved
            .iter()
            .map(|r| LockedPackage {
                name: r.name.clone(),
                version: r.version.clone(),
                source: r.source.clone(),
                checksum: None,
            })
            .collect();
        Self::new(pkgs)
    }

    pub fn from_file(path: &Path) -> Result<Self, String> {
        let text = fs::read_to_string(path).map_err(|e| format!("Failed to read '{:?}': {}", path, e))?;
        toml::from_str(&text).map_err(|e| format!("Failed to parse mote.lock: {}", e))
    }

    pub(crate) fn to_toml_string(&self) -> Result<String, String> {
        let body = toml::to_string_pretty(self).map_err(|e| format!("Failed to serialize mote.lock: {}", e))?;
        Ok(format!("# This file is automatically generated by Mote. Do not edit.\n\n{}", body))
    }

    pub(crate) fn save_to_file(&self, path: &Path) -> Result<(), String> {
        let s = self.to_toml_string()?;
        fs::write(path, s).map_err(|e| format!("Failed to write '{:?}': {}", path, e))
    }
}
